//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xchedulerDBFinalDraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppoinmentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppoinmentDetail()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int AppoinmentId { get; set; }
        public System.DateTime AppoinmentDate { get; set; }
        public System.TimeSpan AppoinmentTime { get; set; }
        public System.TimeSpan AppoinmentEndTime { get; set; }
        public string AppoinmentStatus { get; set; }
        public string PatientID { get; set; }
        public string ReportStaffID { get; set; }
        public int CenterID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CenterDetail CenterDetail { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
