//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xchedulerDBFinalDraft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int RatingId { get; set; }
        public Nullable<int> AppoinmentId { get; set; }
        public Nullable<double> Ratings { get; set; }
        public Nullable<double> Avg_Booking { get; set; }
    
        public virtual AppoinmentDetail AppoinmentDetail { get; set; }
    }
}
